// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		Application: typeof import("./src/components/Application/Application.vue")["default"];
		Block: typeof import("./src/components/GlobalSetting/block.vue")["default"];
		DialogContent: typeof import("./src/components/DialogContent/index.vue")["default"];
		Footer: typeof import("./src/components/Footer/index.vue")["default"];
		FormWrapper: typeof import("./src/components/GlobalSetting/form-wrapper.vue")["default"];
		GlobalSetting: typeof import("./src/components/GlobalSetting/index.vue")["default"];
		LogoTitle: typeof import("./src/components/LogoTitle/index.vue")["default"];
		Menu: typeof import("./src/components/Menu/index.vue")["default"];
		MessageContent: typeof import("./src/components/MessageContent/index.vue")["default"];
		NAffix: typeof import("naive-ui")["NAffix"];
		NAlert: typeof import("naive-ui")["NAlert"];
		NAvatar: typeof import("naive-ui")["NAvatar"];
		Navbar: typeof import("./src/components/Navbar/index.vue")["default"];
		NBadge: typeof import("naive-ui")["NBadge"];
		NButton: typeof import("naive-ui")["NButton"];
		NCard: typeof import("naive-ui")["NCard"];
		NCarousel: typeof import("naive-ui")["NCarousel"];
		NCheckbox: typeof import("naive-ui")["NCheckbox"];
		NCheckboxGroup: typeof import("naive-ui")["NCheckboxGroup"];
		NCol: typeof import("naive-ui")["NCol"];
		NColorPicker: typeof import("naive-ui")["NColorPicker"];
		NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
		NDatePicker: typeof import("naive-ui")["NDatePicker"];
		NDescriptions: typeof import("naive-ui")["NDescriptions"];
		NDescriptionsItem: typeof import("naive-ui")["NDescriptionsItem"];
		NDialogProvider: typeof import("naive-ui")["NDialogProvider"];
		NDivider: typeof import("naive-ui")["NDivider"];
		NDrawer: typeof import("naive-ui")["NDrawer"];
		NDrawerContent: typeof import("naive-ui")["NDrawerContent"];
		NDropdown: typeof import("naive-ui")["NDropdown"];
		NEmpty: typeof import("naive-ui")["NEmpty"];
		NForm: typeof import("naive-ui")["NForm"];
		NFormItem: typeof import("naive-ui")["NFormItem"];
		NFormItemRow: typeof import("naive-ui")["NFormItemRow"];
		NGi: typeof import("naive-ui")["NGi"];
		NGlobalStyle: typeof import("naive-ui")["NGlobalStyle"];
		NGrid: typeof import("naive-ui")["NGrid"];
		NGridItem: typeof import("naive-ui")["NGridItem"];
		NIcon: typeof import("naive-ui")["NIcon"];
		NImage: typeof import("naive-ui")["NImage"];
		NInput: typeof import("naive-ui")["NInput"];
		NInputGroup: typeof import("naive-ui")["NInputGroup"];
		NInputNumber: typeof import("naive-ui")["NInputNumber"];
		NLayout: typeof import("naive-ui")["NLayout"];
		NLayoutContent: typeof import("naive-ui")["NLayoutContent"];
		NLayoutFooter: typeof import("naive-ui")["NLayoutFooter"];
		NLayoutSider: typeof import("naive-ui")["NLayoutSider"];
		NLoadingBarProvider: typeof import("naive-ui")["NLoadingBarProvider"];
		NMention: typeof import("naive-ui")["NMention"];
		NMenu: typeof import("naive-ui")["NMenu"];
		NMessageProvider: typeof import("naive-ui")["NMessageProvider"];
		NModal: typeof import("naive-ui")["NModal"];
		NNotificationProvider: typeof import("naive-ui")["NNotificationProvider"];
		Notification: typeof import("./src/components/Notification/index.vue")["default"];
		NPagination: typeof import("naive-ui")["NPagination"];
		NPopconfirm: typeof import("naive-ui")["NPopconfirm"];
		NPopover: typeof import("naive-ui")["NPopover"];
		NPopselect: typeof import("naive-ui")["NPopselect"];
		NRadio: typeof import("naive-ui")["NRadio"];
		NRadioGroup: typeof import("naive-ui")["NRadioGroup"];
		NResult: typeof import("naive-ui")["NResult"];
		NRow: typeof import("naive-ui")["NRow"];
		NSelect: typeof import("naive-ui")["NSelect"];
		NSpace: typeof import("naive-ui")["NSpace"];
		NSwitch: typeof import("naive-ui")["NSwitch"];
		NTabPane: typeof import("naive-ui")["NTabPane"];
		NTabs: typeof import("naive-ui")["NTabs"];
		NTag: typeof import("naive-ui")["NTag"];
		NTooltip: typeof import("naive-ui")["NTooltip"];
		NTree: typeof import("naive-ui")["NTree"];
		NTreeSelect: typeof import("naive-ui")["NTreeSelect"];
		OptionBadge: typeof import("./src/components/OptionBadge/index.vue")["default"];
		OrgSwitch: typeof import("./src/components/OrgSwitch/index.vue")["default"];
		PageContent: typeof import("./src/components/PageContent/index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SearchBox: typeof import("./src/components/SearchBox/index.vue")["default"];
		SidebarStyle: typeof import("./src/components/GlobalSetting/sidebar-style.vue")["default"];
		StyleExample: typeof import("./src/components/StyleExample/index.vue")["default"];
		TabBar: typeof import("./src/components/TabBar/index.vue")["default"];
		TabItem: typeof import("./src/components/TabBar/tab-item.vue")["default"];
		ThemeColor: typeof import("./src/components/GlobalSetting/theme-color.vue")["default"];
		WangEditor: typeof import("./src/components/WangEditor/index.vue")["default"];
	}
}
